backend/src/main/java/com/shbhack/studywithsol/utils/domain/BaseEntity.java, backend/src/main/java/com/shbhack/studywithsol/utils/dto/response/BaseResponseDto.java, backend/src/main/java/com/shbhack/studywithsol/utils/error/dto/ErrorResponseDto.java, backend/src/main/java/com/shbhack/studywithsol/utils/error/enums/ErrorMessage.java, backend/src/main/java/com/shbhack/studywithsol/utils/error/exception/GlobalExceptionHandler.java, backend/src/main/java/com/shbhack/studywithsol/utils/error/exception/custom/BusinessException.java
=> Feat: 공통 기능 구현

backend/src/main/java/com/shbhack/studywithsol/shinhan/domain/Balance.java, backend/src/main/java/com/shbhack/studywithsol/shinhan/domain/Transaction.java
- #17 
- 신한 API Entity에서 사용하는 거래, 잔액 정보 엔티티 생성
- 신한 패키지로 따로 관리할 예정
=> Feat: 신한 API Entity

backend/src/main/java/com/shbhack/studywithsol/account/domain/Account.java, backend/src/main/java/com/shbhack/studywithsol/account/domain/enums/AccountType.java
=> Rename: 계좌 Entity domain안으로 옮기기

backend/build.gradle, backend/src/main/java/com/shbhack/studywithsol/account/controller/AccountController.java, backend/src/main/java/com/shbhack/studywithsol/account/domain/Account.java, backend/src/main/java/com/shbhack/studywithsol/account/dto/request/AccountCreateRequest.java, backend/src/main/java/com/shbhack/studywithsol/account/dto/response/AccountCreateResponse.java, backend/src/main/java/com/shbhack/studywithsol/account/service/AccountService.java
=> Feat: 계좌 생성 API 구현

backend/src/main/java/com/shbhack/studywithsol/account/dto/request/AccountCreateRequest.java
=> Chore: 계좌 생성 request dto 형식 변경

backend/src/main/java/com/shbhack/studywithsol/account/controller/AccountController.java
=> Chore: 경로 변경

backend/src/main/java/com/shbhack/studywithsol/transaction/domain/Transaction.java
=> Feat: 거래 엔티티 구현

backend/src/main/java/com/shbhack/studywithsol/account/domain/Account.java
=> Chore: 거래, 계좌 mapping

backend/src/main/java/com/shbhack/studywithsol/transaction/domain/Transaction.java, backend/src/main/java/com/shbhack/studywithsol/transaction/dto/request/TransactionCreateRequest.java, backend/src/main/java/com/shbhack/studywithsol/transaction/service/TransactionService.java
=> Chore: 거래 생성 - 계좌 설정

backend/src/main/java/com/shbhack/studywithsol/study/controller/StudyController.java, backend/src/main/java/com/shbhack/studywithsol/study/domain/State.java, backend/src/main/java/com/shbhack/studywithsol/study/domain/Study.java, backend/src/main/java/com/shbhack/studywithsol/study/dto/StudyDto.java, backend/src/main/java/com/shbhack/studywithsol/study/service/StudyService.java, backend/src/main/java/com/shbhack/studywithsol/study/service/StudyServiceImpl.java, backend/src/main/java/com/shbhack/studywithsol/utils/error/enums/ErrorMessage.java, backend/src/main/resources/application.yml
- 학습 상태에 따른 STATE ENUM 설정
- 에러 처리
- 버그 수정
=> 학습 상태에 따른 STATE 설정 및 에러 처리

backend/src/main/java/com/shbhack/studywithsol/user/controller/UserController.java, backend/src/main/java/com/shbhack/studywithsol/utils/configuration/EncoderConfiguration.java, backend/src/main/java/com/shbhack/studywithsol/utils/configuration/SecurityConfiguration.java
- userId( pk )를 얻기 위한 Authentication 사용예제  sample 코드 작성
- post 로 오는 모든 접근 일단 모두 허용
=> Fix: Authentication 사용 예제 + 시큐리티 접근 허용

backend/src/main/java/com/shbhack/studywithsol/timer/controller/TimerController.java, backend/src/main/java/com/shbhack/studywithsol/timer/domain/State.java, backend/src/main/java/com/shbhack/studywithsol/timer/domain/Timer.java, backend/src/main/java/com/shbhack/studywithsol/timer/dto/TimerDto.java, backend/src/main/java/com/shbhack/studywithsol/timer/repository/TimerRepository.java, backend/src/main/java/com/shbhack/studywithsol/timer/service/TimerService.java, backend/src/main/java/com/shbhack/studywithsol/timer/service/TimerServiceImpl.java
- 타이머로 학습 후 부모에게 용돈 요청
- 요청이 들어온 학습에 대해 부모가 용돈의 액수를 정하고 지불
=> 학습량으로 용돈 요청하는 로직 완성

backend/src/main/java/com/shbhack/studywithsol/user/controller/UserController.java, backend/src/main/java/com/shbhack/studywithsol/user/domain/Connection.java, backend/src/main/java/com/shbhack/studywithsol/user/domain/Message.java, backend/src/main/java/com/shbhack/studywithsol/user/domain/User.java, backend/src/main/java/com/shbhack/studywithsol/user/dto/request/UserIdCheckRequest.java, backend/src/main/java/com/shbhack/studywithsol/user/dto/response/UserIdCheckResponse.java, backend/src/main/java/com/shbhack/studywithsol/user/repository/CustomMessageRepository.java, backend/src/main/java/com/shbhack/studywithsol/user/repository/MessageRepository.java, backend/src/main/java/com/shbhack/studywithsol/user/repository/impl/CustomMessageRepositoryImpl.java, backend/src/main/java/com/shbhack/studywithsol/user/service/UserService.java, backend/src/main/java/com/shbhack/studywithsol/utils/error/enums/ErrorMessage.java
- 주계좌 여부 확인 기능 추가
- 아이디-이름 체크 기능 추가
- 1원이체 기능 구현
=> 주계좌 여부 확인, 아이디-이름 체크, 1원이체 기능 구현

backend/src/main/java/com/shbhack/studywithsol/user/controller/UserController.java, backend/src/main/java/com/shbhack/studywithsol/user/dto/request/UserRegisterChildRequest.java, backend/src/main/java/com/shbhack/studywithsol/user/service/UserService.java, backend/src/main/java/com/shbhack/studywithsol/utils/error/enums/ErrorMessage.java
=> Feat: 1원인증 메시지 확인 후 부모-자녀 등록

backend/src/main/java/com/shbhack/studywithsol/account/controller/AccountController.java, backend/src/main/java/com/shbhack/studywithsol/account/dto/request/AccountReadRequest.java, backend/src/main/java/com/shbhack/studywithsol/account/dto/response/AccountMainBalanceReadResponse.java, backend/src/main/java/com/shbhack/studywithsol/account/service/AccountService.java
=> Feat: 주계좌 잔액조회

backend/src/main/java/com/shbhack/studywithsol/pocketmoney/controller/PocketMoneyController.java, backend/src/main/java/com/shbhack/studywithsol/pocketmoney/domain/PocketMoney.java, backend/src/main/java/com/shbhack/studywithsol/pocketmoney/dto/request/PocketMoneyCreateRequest.java, backend/src/main/java/com/shbhack/studywithsol/pocketmoney/dto/response/PocketMoneyCreateResponse.java, backend/src/main/java/com/shbhack/studywithsol/pocketmoney/repository/CustomPocketMoneyRepository.java, backend/src/main/java/com/shbhack/studywithsol/pocketmoney/repository/PocketMoneyRepository.java, backend/src/main/java/com/shbhack/studywithsol/pocketmoney/repository/impl/CustomPocketMoneyRepositoryImpl.java, backend/src/main/java/com/shbhack/studywithsol/pocketmoney/service/PocketMoneyService.java
- 용돈 entity
- 용돈 저장 로직
- 용돈 저장 API
- #62
=> Feat: 용돈 저장 API

backend/src/main/java/com/shbhack/studywithsol/user/controller/UserController.java, backend/src/main/java/com/shbhack/studywithsol/user/domain/Connection.java, backend/src/main/java/com/shbhack/studywithsol/user/domain/User.java, backend/src/main/java/com/shbhack/studywithsol/user/dto/request/UserRegisterChildRequest.java, backend/src/main/java/com/shbhack/studywithsol/user/dto/response/UserParentResponse.java, backend/src/main/java/com/shbhack/studywithsol/user/repository/ConnectionRepository.java, backend/src/main/java/com/shbhack/studywithsol/user/service/UserService.java, backend/src/main/java/com/shbhack/studywithsol/utils/error/enums/ErrorMessage.java
- 부모가 자녀와의 관계 - 별칭 추가 
- 자녀가 부모 리스트 조회 api 추가 구현
=> Feat: 관계 별칭추가 , 자녀가 부모 리스트 조회

backend/src/main/java/com/shbhack/studywithsol/pocketmoney/controller/PocketMoneyController.java, backend/src/main/java/com/shbhack/studywithsol/pocketmoney/domain/PocketMoney.java, backend/src/main/java/com/shbhack/studywithsol/pocketmoney/domain/dto/PocketMoneyUpdate.java, backend/src/main/java/com/shbhack/studywithsol/pocketmoney/dto/request/PocketMoneyReadRequest.java, backend/src/main/java/com/shbhack/studywithsol/pocketmoney/dto/request/PocketMoneyUpdateRequest.java, backend/src/main/java/com/shbhack/studywithsol/pocketmoney/dto/response/PocketMoneyReadResponse.java, backend/src/main/java/com/shbhack/studywithsol/pocketmoney/dto/response/PocketMoneyUpdateResponse.java, backend/src/main/java/com/shbhack/studywithsol/pocketmoney/repository/CustomPocketMoneyRepository.java, backend/src/main/java/com/shbhack/studywithsol/pocketmoney/repository/impl/CustomPocketMoneyRepositoryImpl.java, backend/src/main/java/com/shbhack/studywithsol/pocketmoney/service/PocketMoneyService.java, backend/src/main/java/com/shbhack/studywithsol/utils/error/enums/ErrorMessage.java
- 용돈 수정 로직
- 용돈 수정 API
- 용돈 조회 로직
- 용돈 조회 쿼리
- 용돈 조회 API
=> Feat: 용돈 수정, 조회 API

backend/src/main/java/com/shbhack/studywithsol/report/controller/ReportController.java, backend/src/main/java/com/shbhack/studywithsol/report/domain/SpendingReport.java, backend/src/main/java/com/shbhack/studywithsol/report/dto/request/SpendingReportRequest.java, backend/src/main/java/com/shbhack/studywithsol/report/dto/response/SpendingReportResponse.java, backend/src/main/java/com/shbhack/studywithsol/report/repository/CustomSpendingMoneyRepository.java, backend/src/main/java/com/shbhack/studywithsol/report/repository/SpendingMoneyRepository.java, backend/src/main/java/com/shbhack/studywithsol/report/repository/impl/CustomSpendingMoneyRepositoryImpl.java, backend/src/main/java/com/shbhack/studywithsol/report/service/SpendingReportService.java
- 용돈 지출 레포트 entity
- 쿼리 작성
- 로직 작성
- API
- #63
=> Feat: 용돈 지출 레포트

backend/src/main/java/com/shbhack/studywithsol/user/controller/UserController.java
=> Fix: 1원이체 path 변경

backend/src/main/java/com/shbhack/studywithsol/account/controller/AccountController.java, backend/src/main/java/com/shbhack/studywithsol/pocketmoney/service/PocketMoneyService.java, backend/src/main/java/com/shbhack/studywithsol/report/repository/impl/CustomSpendingMoneyRepositoryImpl.java, backend/src/main/java/com/shbhack/studywithsol/user/repository/ConnectionRepository.java
=> Fix: connection repo 생성자로 받기

backend/src/main/java/com/shbhack/studywithsol/user/controller/UserController.java, backend/src/main/java/com/shbhack/studywithsol/user/service/UserService.java
=> Fix: 비밀번호, 이메일 수정시 반환값  수정

backend/src/main/java/com/shbhack/studywithsol/user/dto/response/UserChildInfoResponse.java
- : responsedto  id, userid 구분
=> Fix: responsedto  id, userid 구분

backend/build.gradle, backend/src/main/java/com/shbhack/studywithsol/utils/configuration/SecurityConfiguration.java
=> Fix: CORS 에러 해결

backend/src/main/java/com/shbhack/studywithsol/account/controller/AccountController.java, backend/src/main/java/com/shbhack/studywithsol/pocketmoney/controller/PocketMoneyController.java, backend/src/main/java/com/shbhack/studywithsol/report/controller/ReportController.java, backend/src/main/java/com/shbhack/studywithsol/transaction/controller/TransactionController.java, front-end/study_with_sol/.gitignore
=> Chore: API post 방식으로

front-end/study_with_sol/lib/screens/reports/report_account.dart, front-end/study_with_sol/pubspec.yaml
=> Feat: 지출 레포트 화면 구현

backend/src/main/java/com/shbhack/studywithsol/account/dto/request/AccountOneTransactionRequest.java, backend/src/main/java/com/shbhack/studywithsol/account/dto/request/AccountOwnerReadRequest.java, backend/src/main/java/com/shbhack/studywithsol/account/dto/response/AccountMainBalanceReadResponse.java, backend/src/main/java/com/shbhack/studywithsol/account/dto/response/AccountOneTransactionResponse.java, backend/src/main/java/com/shbhack/studywithsol/account/dto/response/AccountOwnerReadResponse.java, backend/src/main/java/com/shbhack/studywithsol/account/service/AccountService.java, backend/src/main/java/com/shbhack/studywithsol/pocketmoney/controller/PocketMoneyController.java, backend/src/main/java/com/shbhack/studywithsol/pocketmoney/dto/request/PocketMoneyCreateRequest.java, backend/src/main/java/com/shbhack/studywithsol/pocketmoney/dto/request/PocketMoneyReadRequest.java, backend/src/main/java/com/shbhack/studywithsol/pocketmoney/service/PocketMoneyService.java, backend/src/main/java/com/shbhack/studywithsol/report/domain/SpendingReport.java, backend/src/main/java/com/shbhack/studywithsol/report/dto/request/SpendingReportRequest.java, backend/src/main/java/com/shbhack/studywithsol/report/repository/CustomSpendingMoneyRepository.java, backend/src/main/java/com/shbhack/studywithsol/report/repository/impl/CustomSpendingMoneyRepositoryImpl.java, backend/src/main/java/com/shbhack/studywithsol/report/service/SpendingReportService.java
- 용돈 등록
- 용돈 조회
- 지출 레포트 조회
- 잔액조회시 account number
=> Chore: front 연결 이슈 변경

backend/src/main/java/com/shbhack/studywithsol/account/controller/AccountController.java, backend/src/main/java/com/shbhack/studywithsol/account/dto/response/AccountOwnerReadResponse.java, backend/src/main/java/com/shbhack/studywithsol/account/service/AccountService.java
=> Feat: 예금주 조회 API

front-end/study_with_sol/lib/screens/baby/baby_timer_end_screen.dart, front-end/study_with_sol/lib/screens/baby/baby_timer_screen.dart
=> Feat: 학습 타이머 구현

front-end/study_with_sol/lib/main.dart, front-end/study_with_sol/lib/screens/account/account_list_screen.dart, front-end/study_with_sol/lib/screens/parent/parent_plusbaby_1won_screen.dart, front-end/study_with_sol/lib/screens/parent/parent_plusbaby_screen.dart, front-end/study_with_sol/lib/widgets/button_widget.dart
=> 목업처럼 디자인 그리기

front-end/study_with_sol/lib/screens/login_screen.dart
=> Chore: 로그인
